const Event = {
	In: {
		// Deck
		PLAY_PAUSE_A:     'midi-in:play-pause-a',
		PLAY_PAUSE_B:     'midi-in:play-pause-b',
		CUE_A:            'midi-in:cue-a',
		CUE_B:            'midi-in:cue-b',
		JOG_TOUCH_A:      'midi-in:jog-touch-a',
		JOG_TOUCH_B:      'midi-in:jog-touch-b',
		JOG_ROTATE_REV_A: 'midi-in:jog-rorate-prev-a',
		JOG_ROTATE_REV_B: 'midi-in:jog-rorate-prev-b',
		JOG_ROTATE_FWD_A: 'midi-in:jog-rorate-forward-a',
		JOG_ROTATE_FWD_B: 'midi-in:jog-rorate-forward-b',
		JOG_SEARCH_REV_A: 'midi-in:jog-search-prev-a',
		JOG_SEARCH_REV_B: 'midi-in:jog-search-prev-b',
		JOG_SEARCH_FWD_A: 'midi-in:jog-search-forward-a',
		JOG_SEARCH_FWD_B: 'midi-in:jog-search-forward-b',
		SPEED_A:          'midi-in:speed-a',
		SPEED_B:          'midi-in:speed-b',
		RHYTHM_A:         'midi-in:RHYTHM-a',
		RHYTHM_B:         'midi-in:RHYTHM-b',
		MUTE_A:           'midi-in:mute-a',
		MUTE_B:           'midi-in:mute-b',
		SOLO_A:           'midi-in:solo-a',
		SOLO_B:           'midi-in:solo-b',
		SHIFT_A:          'midi-in:shift-a',
		SHIFT_B:          'midi-in:shift-b',

		// Browser
		SELECT_MEDIA_REV: 'midi-in:select-media-prev',
		SELECT_LAYER_REV: 'midi-in:select-layer-prev',
		SELECT_MEDIA_FWD: 'midi-in:select-media-forward',
		SELECT_LAYER_FWD: 'midi-in:select-layer-forward',
		LOAD_MEDIA_A:     'midi-in:load-media-a',
		LOAD_MEDIA_B:     'midi-in:load-media-b',
		SET_DECK_A:       'midi-in:set-deck-a',
		SET_DECK_B:       'midi-in:set-deck-b',
		
		// Blender
		CROSSFADER: 'midi-in:crossfader',
		OPACITY_A:  'midi-in:opacity-a',
		OPACITY_B:  'midi-in:opacity-b',
		OPACITY_1:  'midi-in:opacity-1',
		OPACITY_2:  'midi-in:opacity-2',
		OPACITY_3:  'midi-in:opacity-3',
		OPACITY_4:  'midi-in:opacity-4',
		OPACITY_5:  'midi-in:opacity-5',
		OPACITY_6:  'midi-in:opacity-6',
	}
}